routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\View;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/home', function () {
    return view('home');
});


Route::get('/dashboard', 'DashboardController@index');


//admin

Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function () {

    Route::get('/', function () {
        return view('backend.admin.index');
    })->name('admin.dashboard');

    Route::resource('/category', 'CategoryController');
    Route::resource('/subcategory', 'SubcategoryController');
    Route::resource('/childcategory', 'ChildcategoryController');

    //adminlisting
    Route::get('/allads', 'AdminListingController@index')->name('all.ads');

    //listing reported ad
    Route::get('/reported-ads', 'FraduController@index')->name('all.reported.ads');

});
Route::get('/', 'FrontAdsController@index');


//ads
Route::get('/ads/create', 'AdvertisementController@create')->name('ads.create')->middleware('auth');;
Route::post('/ads/store', 'AdvertisementController@store')->middleware('auth')->name('ads.store');
Route::get('/ads', 'AdvertisementController@index')->name('ads.index')->middleware('auth');
Route::get('/ads/{id}/edit', 'AdvertisementController@edit')->name('ads.edit')->middleware('auth');
Route::put('/ads/{id}/update', 'AdvertisementController@update')->name('ads.update')->middleware('auth');
Route::delete('/ads/{id}/delete', 'AdvertisementController@destroy')->name('ads.destroy')->middleware('auth');

Route::get('/ad-pending', 'AdvertisementController@pendingAds')->name('pending.ad');

//profile
Route::get('/profile', 'ProfileController@index')->name('profile')->middleware('auth');
Route::post('/profile', 'ProfileController@updateProfile')->name('update.profile')->middleware('auth');


//user ads
Route::get('/ads/{userId}/view', 'FrontendController@viewUserAds')->name('show.user.ads');
//frontend

Route::get(
    '/product/{categorySlug}',
    'FrontendController@findBasedOnCategory'
)
    ->name('category.show');

Route::get('/product/{categorySlug}/{subcategorySlug}', 'FrontendController@findBasedOnSubcategory')
    ->name('subcategory.show');


Route::get(
    '/product/{categorySlug}/{subcategorySlug}/{childCategorySlug}',
    'FrontendController@findBasedOnChildcategory'
)
    ->name('childcategory.show');
Route::get('/products/{id}/{slug}', 'FrontendController@show')
    ->name('product.view');

//Message
Route::post('/send/message', 'SendMessageController@store')->middleware('auth');
Route::get('messages', 'SendMessageController@index')->name('messages')->middleware('auth');
Route::get('/users', 'SendMessageController@chatWithThisUser');
Route::get('/message/user/{id}', 'SendMessageController@showMessages');
Route::post('/start-conversation', 'SendMessageController@startConversation');


//login with facebook
Route::get('auth/facebook', 'SocialLoginController@facebookRedirect');

Route::get('auth/facebook/callback', 'SocialLoginController@loginWithFacebook');


//Save ad
Route::post('/ad/save', 'SaveAdController@saveAd');
Route::post('/ad/remove', 'SaveAdController@removeAd')->name('ad.remove');
Route::get('/saved-ads', 'SaveAdController@getMyads')->name('saved.ad');

//report this ad
Route::post('/report-this-ad', 'FraduController@store')->name('report.ad');


//read me route
Route::get('/instructor', function () {
    return view('info');
});

app/Models/Subcategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Category;
use App\Models\Childcategory;
use App\Models\Advertisement;
class Subcategory extends Model
{
    use HasFactory;
    protected $fillable= ['name','category_id','slug'];

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function category(){
        return $this->belongsTo(Category::class,'category_id','id');
    }
   public function childcategories()
   {
       return $this->hasMany(Childcategory::class);
   }

   public function ads()
   {
       return $this->hasMany(Advertisement::class);
   }





   

}

app/Http/Controllers/SubcategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\SubCategoryFormRequest;
use App\Http\Requests\SubCategoryUpdateRequest;
use App\Models\Subcategory;
use Illuminate\Support\Str;

class SubcategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $subcategories = Subcategory::orderBy('category_id')->paginate(5);
        return view('backend.subcategory.index', compact('subcategories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.subcategory.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(SubCategoryFormRequest $request)
    {
        Subcategory::create([
            'name' => $name = $request->name,
            'slug' => Str::slug($name),
            'category_id' => $request->category_id
        ]);
        return back()->with('message', 'Subcategory created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $subcategory = Subcategory::find($id);
        return view('backend.subcategory.edit', compact('subcategory'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(SubCategoryUpdateRequest $request, $id)
    {
        Subcategory::find($id)->update([
            'name' => $request->name,
            'category_id' => $request->category_id
        ]);
        return redirect()->route('subcategory.index')
            ->with('message', 'Subcategory updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Subcategory::find($id)->delete();
        return back()->with('message', 'Subcategory removed');
    }
}

resources/views/backend/subcategory/create.blade.php
@extends('backend.layouts.master')
@section('content')
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row justify-content-center">
                <div class="col-md-10">
                    @include('backend.inc.message')
                    <h4>Add SubCategory</h4>
                    <div class="card">

                        <div class="card-body">

                            <form class="forms-sample" action="{{ route('subcategory.store') }}" method="post">@csrf
                                <div class="form-group">
                                    <label for="name">Name</label>
                                    <input type="text" name="name" class="form-control @error('name') is-invalid @enderror"
                                        placeholder="name of subcategory">
                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>
                                                {{ $message }}
                                            </strong>

                                        </span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="name">Choose category</label>
                                    <select class="form-control @error('category_id') is-invalid @enderror" name="category_id">
                                        <option value="">Select category</option>
                                        @foreach (App\Models\Category::all() as $category)
                                            <option value="{{ $category->id }}">{{ $category->name }}</option>Í
                                        @endforeach
                                    </select>
                                    @error('category_id')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>
                                                {{ $message }}
                                            </strong>

                                        </span>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary">Save</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/backend/subcategory/edit.blade.php
@extends('backend.layouts.master')
@section('content')
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row justify-content-center">
                <div class="col-md-10">
                    @include('backend.inc.message')
                    <h4>Update SubCategory</h4>
                    <div class="card">

                        <div class="card-body">

                            <form class="forms-sample" action="{{ route('subcategory.update',[$subcategory->id]) }}" method="post">@csrf
                                @method('PUT')
                                <div class="form-group">
                                    <label for="name">Name</label>
                                    <input type="text" name="name" class="form-control @error('name') is-invalid @enderror"
                                value="{{$subcategory->name}}">
                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>
                                                {{ $message }}
                                            </strong>

                                        </span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="name">Choose category</label>
                                    <select class="form-control @error('category_id') is-invalid @enderror" name="category_id">
                                        <option value="">Select category</option>
                                        @foreach (App\Models\Category::all() as $category)
                                            <option value="{{ $category->id }}" {{$subcategory->category_id == $category->id ? 'selected':''}} >{{ $category->name }}</option>Í
                                        @endforeach
                                    </select>
                                    @error('category_id')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>
                                                {{ $message }}
                                            </strong>

                                        </span>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary">Save</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/backend/subcategory/index.blade.php
@extends('backend.layouts.master')
@section('content')
    <div class="main-panel">
        <div class="content-wrapper">
            @include('backend.inc.message')
            <h4>Manage SubCategory</h4>
            <div class="row justify-content-center">


                <div class="col-lg-12 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Category</th>
                                        <th>Name</th>
                                        <th>Edit</th>
                                        <th>Delete</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @forelse($subcategories as $subcategory)
                                        <tr>
                                            <td>{{$subcategories->firstItem() + ($loop->index)}}</td>
                                            <td class="categrory_{{ $subcategory->category_id }}">
                                                {{ $subcategory->category->name }}</td>
                                            <td>{{ $subcategory->name }}</td>
                                            <td>
                                                <a href="{{ route('subcategory.edit', [$subcategory->id]) }}">
                                                    <button
                                                        class="btn btn-sm btn-info">
                                                        <i class="mdi mdi-table-edit"></i>
                                                    </button>
                                                </a>

                                            </td>
                                            <td>
                                                <!-- Button trigger modal -->
                                                <button type="button" class="btn btn-sm btn-danger" data-toggle="modal"
                                                        data-target="#exampleModal{{ $subcategory->id }}">
                                                    <i class="mdi mdi-delete"></i>
                                                </button>

                                                <!-- Modal -->
                                                <div class="modal fade" id="exampleModal{{ $subcategory->id }}"
                                                     tabindex="-1" aria-labelledby="exampleModalLabel"
                                                     aria-hidden="true">
                                                    <div class="modal-dialog">
                                                        <form
                                                            action="{{ route('subcategory.destroy', $subcategory->id) }}"
                                                            method="post">@csrf
                                                            @method('DELETE')
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                    <h5 class="modal-title" id="exampleModalLabel">
                                                                        Delete
                                                                        confirmation</h5>
                                                                    <button type="button" class="close"
                                                                            data-dismiss="modal"
                                                                            aria-label="Close">
                                                                        <span aria-hidden="true">&times;</span>
                                                                    </button>
                                                                </div>
                                                                <div class="modal-body">
                                                                    <p> Are you sure you want to delete this item ?</p>

                                                                </div>
                                                                <div class="modal-footer">
                                                                    <button type="button" class="btn btn-secondary"
                                                                            data-dismiss="modal">Cancel
                                                                    </button>
                                                                    <button type="submit" class="btn btn-danger">Yes,
                                                                        Delete
                                                                        it
                                                                    </button>
                                                                </div>
                                                            </div>
                                                        </form>
                                                    </div>
                                                </div>


                                            </td>


                                        </tr>
                                    @empty
                                        <td>No subcategory to display</td>
                                    @endforelse


                                    </tbody>
                                </table>
                            </div>
                            <div class="mt-3">
                                {{$subcategories->links()}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <style>
                td.categrory_1 {
                    background-color: aliceblue;
                }

                td.categrory_2 {
                    background-color: bisque;
                }

                td.categrory_3 {
                    background-color: thistle;
                }

                td.categrory_4 {
                    background-color: tomato;
                }

                td.categrory_5 {
                    background-color: gray;
                }

                td.categrory_6 {
                    background-color: unset;
                }

                td.categrory_7 {
                    background-color: springgreen;
                }

                td.categrory_8 {
                    background-color: orchid;
                }

                td.categrory_9 {
                    background-color: pink;
                }


            </style>

@endsection