routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\View;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/home', function () {
    return view('home');
});


Route::get('/dashboard', 'DashboardController@index');


//admin

Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function () {

    Route::get('/', function () {
        return view('backend.admin.index');
    })->name('admin.dashboard');

    Route::resource('/category', 'CategoryController');
    Route::resource('/subcategory', 'SubcategoryController');
    Route::resource('/childcategory', 'ChildcategoryController');

    //adminlisting
    Route::get('/allads', 'AdminListingController@index')->name('all.ads');

    //listing reported ad
    Route::get('/reported-ads', 'FraduController@index')->name('all.reported.ads');

});
Route::get('/', 'FrontAdsController@index');


//ads
Route::get('/ads/create', 'AdvertisementController@create')->name('ads.create')->middleware('auth');;
Route::post('/ads/store', 'AdvertisementController@store')->middleware('auth')->name('ads.store');
Route::get('/ads', 'AdvertisementController@index')->name('ads.index')->middleware('auth');
Route::get('/ads/{id}/edit', 'AdvertisementController@edit')->name('ads.edit')->middleware('auth');
Route::put('/ads/{id}/update', 'AdvertisementController@update')->name('ads.update')->middleware('auth');
Route::delete('/ads/{id}/delete', 'AdvertisementController@destroy')->name('ads.destroy')->middleware('auth');

Route::get('/ad-pending', 'AdvertisementController@pendingAds')->name('pending.ad');

//profile
Route::get('/profile', 'ProfileController@index')->name('profile')->middleware('auth');
Route::post('/profile', 'ProfileController@updateProfile')->name('update.profile')->middleware('auth');


//user ads
Route::get('/ads/{userId}/view', 'FrontendController@viewUserAds')->name('show.user.ads');
//frontend

Route::get(
    '/product/{categorySlug}',
    'FrontendController@findBasedOnCategory'
)
    ->name('category.show');

Route::get('/product/{categorySlug}/{subcategorySlug}', 'FrontendController@findBasedOnSubcategory')
    ->name('subcategory.show');


Route::get(
    '/product/{categorySlug}/{subcategorySlug}/{childCategorySlug}',
    'FrontendController@findBasedOnChildcategory'
)
    ->name('childcategory.show');
Route::get('/products/{id}/{slug}', 'FrontendController@show')
    ->name('product.view');

//Message
Route::post('/send/message', 'SendMessageController@store')->middleware('auth');
Route::get('messages', 'SendMessageController@index')->name('messages')->middleware('auth');
Route::get('/users', 'SendMessageController@chatWithThisUser');
Route::get('/message/user/{id}', 'SendMessageController@showMessages');
Route::post('/start-conversation', 'SendMessageController@startConversation');


//login with facebook
Route::get('auth/facebook', 'SocialLoginController@facebookRedirect');

Route::get('auth/facebook/callback', 'SocialLoginController@loginWithFacebook');


//Save ad
Route::post('/ad/save', 'SaveAdController@saveAd');
Route::post('/ad/remove', 'SaveAdController@removeAd')->name('ad.remove');
Route::get('/saved-ads', 'SaveAdController@getMyads')->name('saved.ad');

//report this ad
Route::post('/report-this-ad', 'FraduController@store')->name('report.ad');


//read me route
Route::get('/instructor', function () {
    return view('info');
});

resources/views/backend/layouts/footer.blade.php
<!-- content-wrapper ends -->
<!-- partial:partials/_footer.html -->
</div>
<footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
        <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © marketplace.com {{date('Y')}}</span>
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"><a href="#" target="_blank">Built by Dennis</span>
    </div>
</footer>
<!-- partial -->
</div>
<!-- main-panel ends -->
</div>
<!-- page-body-wrapper ends -->
</div>
<!-- container-scroller -->

<!-- plugins:js -->
<script src="{{asset('admin/template/vendors/base/vendor.bundle.base.js')}}"></script>
<!-- endinject -->
<!-- Plugin js for this page-->
<script src="{{asset('admin/template/vendors/chart.js/Chart.min.js')}}"></script>
<script src="{{asset('admin/template/vendors/datatables.net/jquery.dataTables.js')}}"></script>
<script src="{{asset('admin/template/vendors/datatables.net-bs4/dataTables.bootstrap4.js')}}"></script>
<!-- End plugin js for this page-->
<!-- inject:js -->
<script src="{{asset('admin/template/js/off-canvas.js')}}"></script>
<script src="{{asset('admin/template/js/hoverable-collapse.js')}}"></script>
<script src="{{asset('admin/template/js/template.js')}}"></script>
<!-- endinject -->
<!-- Custom js for this page-->
<script src="{{asset('admin/template/js/dashboard.js')}}"></script>
<script src="{{asset('admin/template/js/data-table.js')}}"></script>
<script src="{{asset('admin/template/js/jquery.dataTables.js')}}"></script>
<script src="{{asset('admin/template/js/dataTables.bootstrap4.js')}}"></script>
<!-- End custom js for this page-->
<script src="{{asset('admin/template/js/jquery.cookie.js')}}" type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
</body>

</html>

resources/views/backend/layouts/header.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Market Place</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{{asset('admin/template/vendors/mdi/css/materialdesignicons.min.css')}}">
    <link rel="stylesheet" href="{{asset('admin/template/vendors/base/vendor.bundle.base.css')}}">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <link rel="stylesheet" href="{{asset('admin/template/vendors/datatables.net-bs4/dataTables.bootstrap4.css')}}">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{{asset('admin/template/css/style.css')}}">
    <!-- endinject -->
    <link rel="shortcut icon" href="{{asset('admin/template/images/favicon.png')}}"/>

</head>

<body>
<div class="container-scroller">
    <!-- partial:partials/_navbar.html -->
    <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
        <div class="navbar-brand-wrapper d-flex justify-content-center">
            <div class="navbar-brand-inner-wrapper d-flex justify-content-between align-items-center w-100">
                <a class="navbar-brand brand-logo" href="{{route('admin.dashboard')}}"><img
                        src="{{asset('admin/template/images/logo.svg')}}"
                        alt="logo"/></a>
                <a class="navbar-brand brand-logo-mini" href="{{route('admin.dashboard')}}"><img
                        src="{{asset('admin/template/images/logo-mini.svg')}}"
                        alt="logo"/></a>
                <button class="navbar-toggler navbar-toggler align-self-center" type="button"
                        data-toggle="minimize">
                    <span class="mdi mdi-sort-variant"></span>
                </button>
            </div>
        </div>
        <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
            <ul class="navbar-nav mr-lg-4 w-100">
                <li class="nav-item nav-search d-none d-lg-block w-100">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            {{-- <span class="input-group-text" id="search">
                                <i class="mdi mdi-magnify"></i>
                            </span> --}}
                        </div>
                        {{-- <input type="text" class="form-control" placeholder="Search now" aria-label="search"
                            aria-describedby="search"> --}}
                    </div>
                </li>
            </ul>
            <ul class="navbar-nav navbar-nav-right">
                <li class="nav-item dropdown mr-1">
                    <a class="nav-link count-indicator dropdown-toggle d-flex justify-content-center align-items-center"
                       id="messageDropdown" href="#" data-toggle="dropdown">
                        {{-- <i class="mdi mdi-message-text mx-0"></i> --}}
                        {{-- <span class="count"></span> --}}
                    </a>

                </li>
                <li class="nav-item nav-profile dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
                        {{-- <img src="images/faces/face5.jpg" alt="profile" /> --}}
                        <span class="nav-profile-name">{{Auth::user()->name}}</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right navbar-dropdown"
                         aria-labelledby="profileDropdown">

                        <a class="dropdown-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();">
                            <i class="mdi mdi-logout text-primary"></i>
                            Logout
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                            @csrf
                        </form>
                    </div>
                </li>
            </ul>
            <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
                    data-toggle="offcanvas">
                <span class="mdi mdi-menu"></span>
            </button>
        </div>
    </nav>

resources/views/backend/layouts/master.blade.php
@include('backend.layouts.header')
@include('backend.layouts.sidebar')
@yield('content')
@include('backend.layouts.footer')

resources/views/backend/layouts/sidebar.blade.php
<div class="container-fluid page-body-wrapper">
    <!-- partial:partials/_sidebar.html -->
    <nav class="sidebar sidebar-offcanvas" id="sidebar">
        <ul class="nav ">
            <li class="nav-item {{ request()->is('subcategory') ? 'active' : '' }} ">
                <a class="nav-link" href="{{route('admin.dashboard')}}">
                    <i class="mdi mdi-home menu-icon"></i>
                    <span class="menu-title">Dashboard</span>
                </a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" data-toggle="collapse" href="#auth" aria-expanded="false" aria-controls="auth">
                    <i class="mdi mdi-circle-outline menu-icon"></i>
                    <span class="menu-title">Category</span>
                    <i class="menu-arrow"></i>
                </a>
                <div class="collapse" id="auth">
                    <ul class="nav flex-column sub-menu">
                        <li class="nav-item "> <a class="nav-link " href="{{ route('category.create') }}">Add</a></li>
                        <li class="nav-item"> <a class="nav-link" href="{{ route('category.index') }}">Manage</a></li>
                    </ul>
                </div>
            </li>
            <li class="nav-item active">
                <a class="nav-link" data-toggle="collapse" href="#ui-basic1" aria-expanded="false"
                    aria-controls="ui-basic1">
                    <i class="mdi mdi-circle-outline menu-icon"></i>
                    <span class="menu-title">Subcategory</span>
                    <i class="menu-arrow"></i>
                </a>
                <div class="collapse" id="ui-basic1">
                    <ul class="nav flex-column sub-menu">
                        <li class="nav-item "> <a class="nav-link" href="{{ route('subcategory.create') }}">Add</a></li>
                        <li class="nav-item"> <a class="nav-link" href="{{ route('subcategory.index') }}">Manage</a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="collapse" href="#ui-basic2" aria-expanded="false"
                    aria-controls="ui-basic2">
                    <i class="mdi mdi-circle-outline menu-icon"></i>
                    <span class="menu-title">Childcategory</span>
                    <i class="menu-arrow"></i>
                </a>
                <div class="collapse" id="ui-basic2">
                    <ul class="nav flex-column sub-menu">
                        <li class="nav-item"> <a class="nav-link" href="{{ route('childcategory.create') }}">Add</a>
                        </li>
                        <li class="nav-item"> <a class="nav-link" href="{{ route('childcategory.index') }}">Manage</a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('all.ads') }}">
                    <i class="mdi mdi-account-multiple menu-icon"></i>
                    <span class="menu-title"> All advertisements</span>
                </a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{{route('all.reported.ads')}}">
                    <i class="mdi mdi-chart-pie menu-icon"></i>
                    <span class="menu-title">Reported ads</span>
                </a>
            </li>
            {{-- <li class="nav-item">
                <a class="nav-link" href="pages/tables/basic-table.html">
                    <i class="mdi mdi-grid-large menu-icon"></i>
                    <span class="menu-title">Tables</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="pages/icons/mdi.html">
                    <i class="mdi mdi-emoticon menu-icon"></i>
                    <span class="menu-title">Icons</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="collapse" href="#auth" aria-expanded="false" aria-controls="auth">
                    <i class="mdi mdi-account menu-icon"></i>
                    <span class="menu-title">User Pages</span>
                    <i class="menu-arrow"></i>
                </a>
                <div class="collapse" id="auth">
                    <ul class="nav flex-column sub-menu">
                        <li class="nav-item"> <a class="nav-link" href="pages/samples/login.html"> Login </a></li>
                        <li class="nav-item"> <a class="nav-link" href="pages/samples/login-2.html"> Login 2 </a></li>
                        <li class="nav-item"> <a class="nav-link" href="pages/samples/register.html"> Register </a></li>
                        <li class="nav-item"> <a class="nav-link" href="pages/samples/register-2.html"> Register 2 </a>
                        </li>
                        <li class="nav-item"> <a class="nav-link" href="pages/samples/lock-screen.html"> Lockscreen </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="documentation/documentation.html">
                    <i class="mdi mdi-file-document-box-outline menu-icon"></i>
                    <span class="menu-title">Documentation</span>
                </a>
            </li> --}}
        </ul>
    </nav>